# Generated by Django 5.1.2 on 2024-10-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OceanMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('salinity', models.FloatField()),
                ('depth', models.IntegerField()),
            ],
        ),
    ]
