# Generated by Django 5.1.2 on 2024-11-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IronMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('depth', models.FloatField(blank=True, null=True)),
                ('dfe', models.FloatField(blank=True, null=True)),
                ('rrs_443', models.FloatField()),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.DeleteModel(
            name='OceanMetric',
        ),
    ]
