# Generated by Django 5.1.2 on 2024-11-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ironmeasurement_delete_oceanmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('soil_moisture', models.FloatField()),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
