# Generated by Django 5.1.2 on 2024-11-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_soilmoisture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilmoisture',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
