# Generated by Django 5.1.2 on 2024-11-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_soilmoisture_soil_moisture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilmoisture',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soilmoisture',
            name='longitude',
        ),
        migrations.AddField(
            model_name='soilmoisture',
            name='sensorZ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilmoisture',
            name='site',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
    ]
