# Generated by Django 5.1.2 on 2024-11-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_soilmoisture_latitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ironmeasurement',
            index=models.Index(fields=['cruise'], name='dashboard_i_cruise_85327a_idx'),
        ),
        migrations.AddIndex(
            model_name='ironmeasurement',
            index=models.Index(fields=['datetime'], name='dashboard_i_datetim_37b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='ironmeasurement',
            index=models.Index(fields=['depth'], name='dashboard_i_depth_77e3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='soilmoisture',
            index=models.Index(fields=['site'], name='dashboard_s_site_a891b2_idx'),
        ),
        migrations.AddIndex(
            model_name='soilmoisture',
            index=models.Index(fields=['datetime'], name='dashboard_s_datetim_062f5d_idx'),
        ),
    ]
